const TransactionConstants = {
    FETCH_TRANSACTION = "FETCH_TRANSACTION",
    FETCH_TRANSACTION_SUCCESS = "FETCH_TRANSACTION_SUCCESS",
    FETCH_TRANSACTION_FAILURE = "FETCH_TRANSACTION_FAILURE",

    MAKE_TRANSACTION = "MAKE_TRANSACTION",
    MAKE_TRANSACTION_SUCCESS = "MAKE_TRANSACTION_SUCCESS",
    MAKE_TRANSACTION_FAILURE = "MAKE_TRANSACTION_FAILURE"
}
export default TransactionConstants