const userConstants = {
    FETCH_USER: 'FETCH_USER',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',

    SET_USER_BALANCE: 'SET_USER_BALANCE',
    
    LOGIN: "LOGIN",
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT: "LOGOUT",
}

export default userConstants